elasticsearch:
  image: elasticsearch
  ports:
    - 9200:9200
    - 9300:9300

fluentd:
  build: .
  links:
    - elasticsearch
  volumes:
    - .:/home/fluent

kibana:
  image: kibana
  ports:
    - 5601:5601
  links:
    - elasticsearch
